PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=4.78 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=3.62 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=2.02 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=2.22 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 2.026/3.164/4.783/1.122 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.3 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=12.3 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 12.291/12.338/12.391/0.143 ms
fatal: Not a git repository (or any of the parent directories): .git
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 140522280440320 whose fp = <socket._fileobject object at 0x7fcde501ddd0>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
Traceback (most recent call last):
  File "/home/tina/Documents/repos/networking/check.py", line 120, in <module>
    main()
  File "/home/tina/Documents/repos/networking/check.py", line 119, in main
    writeResults(str(status))
  File "/home/tina/Documents/repos/networking/check.py", line 95, in writeResults
    monitoring_version = str(utils.monitoringVersion())
  File "/home/tina/Documents/repos/networking/utils.py", line 63, in monitoringVersion
    return subprocess.check_output(args).replace('\n', '')
  File "/usr/lib64/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128
PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=1.25 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=1.52 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=1.50 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=13.2 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 1.256/4.386/13.259/5.124 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=12.6 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=13.6 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=12.3 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 12.230/12.719/13.611/0.560 ms
fatal: Not a git repository (or any of the parent directories): .git
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 139799273239040 whose fp = <socket._fileobject object at 0x7f258e6b7dd0>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
Traceback (most recent call last):
  File "/home/tina/Documents/repos/networking/check.py", line 120, in <module>
    main()
  File "/home/tina/Documents/repos/networking/check.py", line 119, in main
    writeResults(str(status))
  File "/home/tina/Documents/repos/networking/check.py", line 95, in writeResults
    monitoring_version = str(utils.monitoringVersion())
  File "/home/tina/Documents/repos/networking/utils.py", line 63, in monitoringVersion
    return subprocess.check_output(args).replace('\n', '')
  File "/usr/lib64/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128
PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=1.31 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=1.53 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=9.52 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=1.83 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 1.316/3.552/9.526/3.454 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.1 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=12.3 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=12.2 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 12.154/12.272/12.372/0.156 ms
fatal: Not a git repository (or any of the parent directories): .git
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 139968595038720 whose fp = <socket._fileobject object at 0x7f4cfac91dd0>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
Traceback (most recent call last):
  File "/home/tina/Documents/repos/networking/check.py", line 120, in <module>
    main()
  File "/home/tina/Documents/repos/networking/check.py", line 119, in main
    writeResults(str(status))
  File "/home/tina/Documents/repos/networking/check.py", line 95, in writeResults
    monitoring_version = str(utils.monitoringVersion())
  File "/home/tina/Documents/repos/networking/utils.py", line 63, in monitoringVersion
    return subprocess.check_output(args).replace('\n', '')
  File "/usr/lib64/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128
PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=1.39 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=6.78 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=9.82 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=16.0 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 1.398/8.502/16.003/5.278 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=13.1 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=12.1 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 12.115/12.431/13.131/0.422 ms
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 140133824020920 whose fp = <socket._fileobject object at 0x7f7373336dd0>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
Traceback (most recent call last):
  File "/home/tina/Documents/repos/networking/check.py", line 120, in <module>
    main()
  File "/home/tina/Documents/repos/networking/check.py", line 119, in main
    writeResults(str(status))
  File "/home/tina/Documents/repos/networking/check.py", line 95, in writeResults
    monitoring_version = str(utils.monitoringVersion())
  File "/home/tina/Documents/repos/networking/utils.py", line 64, in monitoringVersion
    gg_matches = subprocess.check_output(["git", gd, wt, "grep"] + gg_opt)
NameError: global name 'gg_opt' is not defined
PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=1.29 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=2.12 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=1.76 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=9.74 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 1.290/3.730/9.744/3.485 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=12.3 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.3 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=12.3 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=12.1 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 12.187/12.317/12.388/0.077 ms
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 139984836157880 whose fp = <socket._fileobject object at 0x7f50c2d4edd0>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
Traceback (most recent call last):
  File "/home/tina/Documents/repos/networking/check.py", line 120, in <module>
    main()
  File "/home/tina/Documents/repos/networking/check.py", line 119, in main
    writeResults(str(status))
  File "/home/tina/Documents/repos/networking/check.py", line 95, in writeResults
    monitoring_version = str(utils.monitoringVersion())
  File "/home/tina/Documents/repos/networking/utils.py", line 64, in monitoringVersion
    repo_path = '/home/tina/Documents/repos/networking'
NameError: global name 'gg_opt' is not defined
PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=1.63 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=1.99 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=1.66 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=1.55 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 1.558/1.715/1.999/0.171 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.4 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=12.3 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=28.4 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 12.265/16.347/28.418/6.969 ms
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 139765429813688 whose fp = <socket._fileobject object at 0x7f1dad31ee50>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
Traceback (most recent call last):
  File "/home/tina/Documents/repos/networking/check.py", line 120, in <module>
    main()
  File "/home/tina/Documents/repos/networking/check.py", line 119, in main
    writeResults(str(status))
  File "/home/tina/Documents/repos/networking/check.py", line 95, in writeResults
    monitoring_version = str(utils.monitoringVersion())
  File "/home/tina/Documents/repos/networking/utils.py", line 70, in monitoringVersion
    gg_matches = subprocess.check_output(["git", gd, wt])
  File "/usr/lib64/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['git', '--git-dir=/home/tina/Documents/repos/networking/.git', '--work-tree=/home/tina/Documents/repos/networking']' returned non-zero exit status 1
PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=1.30 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=1.50 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=1.53 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=1.53 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 1.303/1.469/1.539/0.100 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.3 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=12.4 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 12.292/12.344/12.413/0.123 ms
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 139776386900408 whose fp = <socket._fileobject object at 0x7f203a49cdd0>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
Traceback (most recent call last):
  File "/home/tina/Documents/repos/networking/check.py", line 120, in <module>
    main()
  File "/home/tina/Documents/repos/networking/check.py", line 119, in main
    writeResults(str(status))
  File "/home/tina/Documents/repos/networking/check.py", line 95, in writeResults
    monitoring_version = str(utils.monitoringVersion())
  File "/home/tina/Documents/repos/networking/utils.py", line 68, in monitoringVersion
    gg_matches = subprocess.check_output([args, gd, wt])
  File "/usr/lib64/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
AttributeError: 'list' object has no attribute 'rfind'
PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=2.24 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=1.47 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=1.97 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=1.42 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 1.426/1.782/2.247/0.346 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=12.3 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.4 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=12.3 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=12.2 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 12.220/12.362/12.499/0.098 ms
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 140357767193016 whose fp = <socket._fileobject object at 0x7fa79740ee50>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
args: 
[['git', 'rev-parse', 'HEAD'], '--git-dir=/home/tina/Documents/repos/networking/.git', '--work-tree=/home/tina/Documents/repos/networking']
Traceback (most recent call last):
  File "/home/tina/Documents/repos/networking/check.py", line 120, in <module>
    main()
  File "/home/tina/Documents/repos/networking/check.py", line 119, in main
    writeResults(str(status))
  File "/home/tina/Documents/repos/networking/check.py", line 95, in writeResults
    monitoring_version = str(utils.monitoringVersion())
  File "/home/tina/Documents/repos/networking/utils.py", line 71, in monitoringVersion
    gg_matches = subprocess.check_output([args, gd, wt])
  File "/usr/lib64/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
AttributeError: 'list' object has no attribute 'rfind'
PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=7.94 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=1.55 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=1.51 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=1.83 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3003ms
rtt min/avg/max/mdev = 1.514/3.211/7.947/2.737 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.1 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=12.2 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 12.131/12.212/12.267/0.092 ms
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 140605112562104 whose fp = <socket._fileobject object at 0x7fe12e2fbe50>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
Traceback (most recent call last):
  File "/home/tina/Documents/repos/networking/check.py", line 120, in <module>
    main()
  File "/home/tina/Documents/repos/networking/check.py", line 119, in main
    writeResults(str(status))
  File "/home/tina/Documents/repos/networking/check.py", line 95, in writeResults
    monitoring_version = str(utils.monitoringVersion())
  File "/home/tina/Documents/repos/networking/utils.py", line 68, in monitoringVersion
    args = command_args.append(gd, wt)
TypeError: append() takes exactly one argument (2 given)
PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=1.24 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=1.61 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=1.56 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=1.50 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 1.240/1.481/1.616/0.144 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.4 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=12.3 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=12.6 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 12.223/12.406/12.649/0.179 ms
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 140516186706360 whose fp = <socket._fileobject object at 0x7fcc79cade50>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
args: 
['git', 'rev-parse', 'HEAD', '--git-dir=/home/tina/Documents/repos/networking/.git', '--work-tree=/home/tina/Documents/repos/networking']
Traceback (most recent call last):
  File "/home/tina/Documents/repos/networking/check.py", line 120, in <module>
    main()
  File "/home/tina/Documents/repos/networking/check.py", line 119, in main
    writeResults(str(status))
  File "/home/tina/Documents/repos/networking/check.py", line 95, in writeResults
    monitoring_version = str(utils.monitoringVersion())
  File "/home/tina/Documents/repos/networking/utils.py", line 73, in monitoringVersion
    gg_matches = subprocess.check_output([args, gd, wt])
  File "/usr/lib64/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
AttributeError: 'list' object has no attribute 'rfind'
PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=1.28 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=1.88 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=1.41 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=1.55 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3003ms
rtt min/avg/max/mdev = 1.287/1.534/1.887/0.224 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=12.3 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=12.4 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=12.7 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 12.255/12.445/12.713/0.190 ms
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 140181551956408 whose fp = <socket._fileobject object at 0x7f7e9001ce50>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
args: 
['git', 'rev-parse', 'HEAD', '--git-dir=/home/tina/Documents/repos/networking/.git', '--work-tree=/home/tina/Documents/repos/networking']
Traceback (most recent call last):
  File "/home/tina/Documents/repos/networking/check.py", line 120, in <module>
    main()
  File "/home/tina/Documents/repos/networking/check.py", line 119, in main
    writeResults(str(status))
  File "/home/tina/Documents/repos/networking/check.py", line 95, in writeResults
    monitoring_version = str(utils.monitoringVersion())
  File "/home/tina/Documents/repos/networking/utils.py", line 73, in monitoringVersion
    gg_matches = subprocess.check_output([args, gd, wt])
  File "/usr/lib64/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
AttributeError: 'list' object has no attribute 'rfind'
PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=1.17 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=1.35 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=2.08 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=5.01 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 1.176/2.410/5.018/1.544 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.4 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=12.4 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=12.4 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 12.231/12.376/12.435/0.115 ms
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 139737694323128 whose fp = <socket._fileobject object at 0x7f173807ce50>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
args: 
['git', 'rev-parse', 'HEAD', '--git-dir=/home/tina/Documents/repos/networking/.git', '--work-tree=/home/tina/Documents/repos/networking']
Traceback (most recent call last):
  File "/home/tina/Documents/repos/networking/check.py", line 120, in <module>
    main()
  File "/home/tina/Documents/repos/networking/check.py", line 119, in main
    writeResults(str(status))
  File "/home/tina/Documents/repos/networking/check.py", line 95, in writeResults
    monitoring_version = str(utils.monitoringVersion())
  File "/home/tina/Documents/repos/networking/utils.py", line 73, in monitoringVersion
    gg_matches = subprocess.check_output([args, gd, wt])
  File "/usr/lib64/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
AttributeError: 'list' object has no attribute 'rfind'
PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=1.44 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=1.30 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=1.35 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=1.49 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 1.307/1.398/1.491/0.086 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=12.3 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.3 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=12.1 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=34.7 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 12.161/17.908/34.748/9.722 ms
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 140592631210424 whose fp = <socket._fileobject object at 0x7fde463d6e50>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
args: 
['git', 'rev-parse', 'HEAD', '--git-dir=/home/tina/Documents/repos/networking/.git', '--work-tree=/home/tina/Documents/repos/networking']
Traceback (most recent call last):
  File "/home/tina/Documents/repos/networking/check.py", line 120, in <module>
    main()
  File "/home/tina/Documents/repos/networking/check.py", line 119, in main
    writeResults(str(status))
  File "/home/tina/Documents/repos/networking/check.py", line 95, in writeResults
    monitoring_version = str(utils.monitoringVersion())
  File "/home/tina/Documents/repos/networking/utils.py", line 73, in monitoringVersion
    gg_matches = subprocess.check_output([args, gd, wt])
  File "/usr/lib64/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
AttributeError: 'list' object has no attribute 'rfind'
PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=1.24 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=1.55 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=1.17 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=1.21 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3003ms
rtt min/avg/max/mdev = 1.170/1.294/1.554/0.158 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=12.0 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.1 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=12.4 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=12.1 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3003ms
rtt min/avg/max/mdev = 12.018/12.190/12.444/0.174 ms
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 140173994140088 whose fp = <socket._fileobject object at 0x7f7ccd86ae50>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
args: 
['git', 'rev-parse', 'HEAD', '--git-dir=/home/tina/Documents/repos/networking/.git', '--work-tree=/home/tina/Documents/repos/networking']
Traceback (most recent call last):
  File "/home/tina/Documents/repos/networking/check.py", line 120, in <module>
    main()
  File "/home/tina/Documents/repos/networking/check.py", line 119, in main
    writeResults(str(status))
  File "/home/tina/Documents/repos/networking/check.py", line 95, in writeResults
    monitoring_version = str(utils.monitoringVersion())
  File "/home/tina/Documents/repos/networking/utils.py", line 73, in monitoringVersion
    gg_matches = subprocess.check_output([args, gd, wt])
  File "/usr/lib64/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
AttributeError: 'list' object has no attribute 'rfind'
PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=1.26 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=36.0 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=1.57 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=1.50 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 1.262/10.096/36.037/14.977 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=12.5 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=12.3 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 12.213/12.345/12.539/0.124 ms
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 140241712615864 whose fp = <socket._fileobject object at 0x7f8c91dc9e50>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
args: 
['git', 'rev-parse', 'HEAD', '--git-dir=/home/tina/Documents/repos/networking/.git', '--work-tree=/home/tina/Documents/repos/networking']
Traceback (most recent call last):
  File "/home/tina/Documents/repos/networking/check.py", line 120, in <module>
    main()
  File "/home/tina/Documents/repos/networking/check.py", line 119, in main
    writeResults(str(status))
  File "/home/tina/Documents/repos/networking/check.py", line 95, in writeResults
    monitoring_version = str(utils.monitoringVersion())
  File "/home/tina/Documents/repos/networking/utils.py", line 73, in monitoringVersion
    gg_matches = subprocess.check_output([args, gd, wt])
  File "/usr/lib64/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
AttributeError: 'list' object has no attribute 'rfind'
PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=1.54 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=1.61 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=1.74 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=1.54 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 1.542/1.613/1.748/0.092 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=12.1 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=12.2 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 12.180/12.216/12.238/0.137 ms
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 140699456991672 whose fp = <socket._fileobject object at 0x7ff7258d7e50>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
args: 
['git', 'rev-parse', 'HEAD', '--git-dir=/home/tina/Documents/repos/networking/.git', '--work-tree=/home/tina/Documents/repos/networking']
Traceback (most recent call last):
  File "/home/tina/Documents/repos/networking/check.py", line 120, in <module>
    main()
  File "/home/tina/Documents/repos/networking/check.py", line 119, in main
    writeResults(str(status))
  File "/home/tina/Documents/repos/networking/check.py", line 95, in writeResults
    monitoring_version = str(utils.monitoringVersion())
  File "/home/tina/Documents/repos/networking/utils.py", line 73, in monitoringVersion
    gg_matches = subprocess.check_output([args, gd, wt])
  File "/usr/lib64/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
AttributeError: 'list' object has no attribute 'rfind'
PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=3.21 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=1.63 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=5.49 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=11.3 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 1.639/5.435/11.395/3.703 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=12.1 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.9 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=12.1 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3003ms
rtt min/avg/max/mdev = 12.102/12.350/12.958/0.363 ms
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 139826285162936 whose fp = <socket._fileobject object at 0x7f2bd874be50>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
args: 
['git', 'rev-parse', 'HEAD', '--git-dir=/home/tina/Documents/repos/networking/.git', '--work-tree=/home/tina/Documents/repos/networking']
Traceback (most recent call last):
  File "/home/tina/Documents/repos/networking/check.py", line 120, in <module>
    main()
  File "/home/tina/Documents/repos/networking/check.py", line 119, in main
    writeResults(str(status))
  File "/home/tina/Documents/repos/networking/check.py", line 95, in writeResults
    monitoring_version = str(utils.monitoringVersion())
  File "/home/tina/Documents/repos/networking/utils.py", line 73, in monitoringVersion
    gg_matches = subprocess.check_output([args, gd, wt])
  File "/usr/lib64/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
AttributeError: 'list' object has no attribute 'rfind'
PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=1.46 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=1.66 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=1.76 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=1.41 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 1.415/1.575/1.760/0.146 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=12.1 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=12.1 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=12.2 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 12.138/12.204/12.297/0.149 ms
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 140377391006136 whose fp = <socket._fileobject object at 0x7fac28ec8e50>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
args: 
['git', 'rev-parse', 'HEAD', '--git-dir=/home/tina/Documents/repos/networking/.git', '--work-tree=/home/tina/Documents/repos/networking']
Traceback (most recent call last):
  File "/home/tina/Documents/repos/networking/check.py", line 120, in <module>
    main()
  File "/home/tina/Documents/repos/networking/check.py", line 119, in main
    writeResults(str(status))
  File "/home/tina/Documents/repos/networking/check.py", line 95, in writeResults
    monitoring_version = str(utils.monitoringVersion())
  File "/home/tina/Documents/repos/networking/utils.py", line 73, in monitoringVersion
    gg_matches = subprocess.check_output([args, gd, wt])
  File "/usr/lib64/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
AttributeError: 'list' object has no attribute 'rfind'
PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=1.56 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=4.65 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=10.3 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=1.48 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 1.480/4.507/10.328/3.596 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=12.2 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3003ms
rtt min/avg/max/mdev = 12.240/12.269/12.287/0.017 ms
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 139883562840576 whose fp = <socket._fileobject object at 0x7f392e78ce50>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
args: 
['git', 'rev-parse', 'HEAD', '--git-dir=/home/tina/Documents/repos/networking/.git', '--work-tree=/home/tina/Documents/repos/networking']
Traceback (most recent call last):
  File "/home/tina/Documents/repos/networking/check.py", line 120, in <module>
    main()
  File "/home/tina/Documents/repos/networking/check.py", line 119, in main
    writeResults(str(status))
  File "/home/tina/Documents/repos/networking/check.py", line 95, in writeResults
    monitoring_version = str(utils.monitoringVersion())
  File "/home/tina/Documents/repos/networking/utils.py", line 73, in monitoringVersion
    gg_matches = subprocess.check_output([args, gd, wt])
  File "/usr/lib64/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
AttributeError: 'list' object has no attribute 'rfind'
PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=1.17 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=1.98 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=1.64 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=1.63 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 1.171/1.608/1.984/0.291 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=13.1 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.7 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=12.1 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3002ms
rtt min/avg/max/mdev = 12.156/12.594/13.170/0.417 ms
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 140474592473600 whose fp = <socket._fileobject object at 0x7fc2ca954dd0>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
args: 
['git', 'rev-parse', 'HEAD', '--git-dir=/home/tina/Documents/repos/networking/.git', '--work-tree=/home/tina/Documents/repos/networking']
Traceback (most recent call last):
  File "/home/tina/Documents/repos/networking/check.py", line 120, in <module>
    main()
  File "/home/tina/Documents/repos/networking/check.py", line 119, in main
    writeResults(str(status))
  File "/home/tina/Documents/repos/networking/check.py", line 95, in writeResults
    monitoring_version = str(utils.monitoringVersion())
  File "/home/tina/Documents/repos/networking/utils.py", line 73, in monitoringVersion
    response = subprocess.check_output([args, gd, wt])
  File "/usr/lib64/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
AttributeError: 'list' object has no attribute 'rfind'
PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=2.81 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=12.3 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=1.69 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=1.46 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 1.467/4.579/12.346/4.513 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=12.1 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=12.3 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3003ms
rtt min/avg/max/mdev = 12.182/12.252/12.351/0.151 ms
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 139942863937976 whose fp = <socket._fileobject object at 0x7f46fd17add0>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
args: 
['git', 'rev-parse', 'HEAD', '--git-dir=/home/tina/Documents/repos/networking/.git', '--work-tree=/home/tina/Documents/repos/networking']
Traceback (most recent call last):
  File "/home/tina/Documents/repos/networking/check.py", line 120, in <module>
    main()
  File "/home/tina/Documents/repos/networking/check.py", line 119, in main
    writeResults(str(status))
  File "/home/tina/Documents/repos/networking/check.py", line 95, in writeResults
    monitoring_version = str(utils.monitoringVersion())
  File "/home/tina/Documents/repos/networking/utils.py", line 73, in monitoringVersion
    response = subprocess.check_output([args, gd, wt])
  File "/usr/lib64/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
AttributeError: 'list' object has no attribute 'rfind'
PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=1.63 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=1.52 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=1.50 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=1.47 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 1.477/1.534/1.633/0.065 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=12.3 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.1 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=46.5 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=12.2 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 12.195/20.835/46.547/14.845 ms
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 140263729734072 whose fp = <socket._fileobject object at 0x7f91b22f2dd0>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
args: 
['git', 'rev-parse', 'HEAD', '--git-dir=/home/tina/Documents/repos/networking/.git', '--work-tree=/home/tina/Documents/repos/networking']
Traceback (most recent call last):
  File "/home/tina/Documents/repos/networking/check.py", line 120, in <module>
    main()
  File "/home/tina/Documents/repos/networking/check.py", line 119, in main
    writeResults(str(status))
  File "/home/tina/Documents/repos/networking/check.py", line 95, in writeResults
    monitoring_version = str(utils.monitoringVersion())
  File "/home/tina/Documents/repos/networking/utils.py", line 73, in monitoringVersion
    response = subprocess.check_output([args, gd, wt])
  File "/usr/lib64/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
AttributeError: 'list' object has no attribute 'rfind'
PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=1.48 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=1.60 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=1.80 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=1.56 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 1.481/1.615/1.804/0.124 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=13.1 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=12.1 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=12.1 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3003ms
rtt min/avg/max/mdev = 12.157/12.429/13.147/0.430 ms
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 140097447236024 whose fp = <socket._fileobject object at 0x7f6afaf99dd0>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
args: 
['git', 'rev-parse', 'HEAD', '--git-dir=/home/tina/Documents/repos/networking/.git', '--work-tree=/home/tina/Documents/repos/networking']
Traceback (most recent call last):
  File "/home/tina/Documents/repos/networking/check.py", line 120, in <module>
    main()
  File "/home/tina/Documents/repos/networking/check.py", line 119, in main
    writeResults(str(status))
  File "/home/tina/Documents/repos/networking/check.py", line 95, in writeResults
    monitoring_version = str(utils.monitoringVersion())
  File "/home/tina/Documents/repos/networking/utils.py", line 73, in monitoringVersion
    response = subprocess.check_output([args, gd, wt])
  File "/usr/lib64/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
AttributeError: 'list' object has no attribute 'rfind'
PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=1.55 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=1.73 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=5.09 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=1.75 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 1.554/2.534/5.096/1.481 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=28.6 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.3 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=12.5 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=12.4 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 12.362/16.500/28.655/7.017 ms
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 139860153233848 whose fp = <socket._fileobject object at 0x7f33bb267dd0>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
args: 
['git', 'rev-parse', 'HEAD', '--git-dir=/home/tina/Documents/repos/networking/.git', '--work-tree=/home/tina/Documents/repos/networking']
Traceback (most recent call last):
  File "/home/tina/Documents/repos/networking/check.py", line 120, in <module>
    main()
  File "/home/tina/Documents/repos/networking/check.py", line 119, in main
    writeResults(str(status))
  File "/home/tina/Documents/repos/networking/check.py", line 95, in writeResults
    monitoring_version = str(utils.monitoringVersion())
  File "/home/tina/Documents/repos/networking/utils.py", line 73, in monitoringVersion
    response = subprocess.check_output([args, gd, wt])
  File "/usr/lib64/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
AttributeError: 'list' object has no attribute 'rfind'
PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=1.33 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=1.53 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=1.95 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=5.18 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 1.330/2.499/5.180/1.565 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=12.3 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.4 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=12.3 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=13.3 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 12.341/12.617/13.307/0.422 ms
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 139707069469184 whose fp = <socket._fileobject object at 0x7f1016a5add0>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
args: 
['git', '--git-dir=/home/tina/Documents/repos/networking/.git', '--work-tree=/home/tina/Documents/repos/networking', 'rev-parse', 'HEAD']
Traceback (most recent call last):
  File "/home/tina/Documents/repos/networking/check.py", line 120, in <module>
    main()
  File "/home/tina/Documents/repos/networking/check.py", line 119, in main
    writeResults(str(status))
  File "/home/tina/Documents/repos/networking/check.py", line 95, in writeResults
    monitoring_version = str(utils.monitoringVersion())
  File "/home/tina/Documents/repos/networking/utils.py", line 68, in monitoringVersion
    response = subprocess.check_output([args, gd, wt])
  File "/usr/lib64/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
AttributeError: 'list' object has no attribute 'rfind'
PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=1.40 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=1.66 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=1.67 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=1.61 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 1.400/1.588/1.675/0.110 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=12.4 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.6 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=12.4 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=15.1 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 12.419/13.165/15.185/1.176 ms
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 139993796882944 whose fp = <socket._fileobject object at 0x7f52d8eeddd0>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
args: 
['git', '--git-dir=/home/tina/Documents/repos/networking/.git', '--work-tree=/home/tina/Documents/repos/networking', 'rev-parse', 'HEAD']
response: 
['f921b6945f95f09c3cf2c09e025b97f8f83f1a95']
PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=1.35 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=2.98 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=1.66 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=4.96 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 1.353/2.742/4.964/1.421 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=12.3 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.3 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=12.3 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=12.2 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 12.265/12.317/12.367/0.037 ms
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 140466068075008 whose fp = <socket._fileobject object at 0x7fc0ce7d5dd0>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
args: 
['git', '--git-dir=/home/tina/Documents/repos/networking/.git', '--work-tree=/home/tina/Documents/repos/networking', 'rev-parse', 'HEAD']
response: 
f921b6945f95f09c3cf2c09e025b97f8f83f1a95

PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=1.42 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=1.63 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=1.59 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=48.9 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 1.429/13.414/48.992/20.541 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=18.1 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.3 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=12.3 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=12.2 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 12.215/13.756/18.143/2.533 ms
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 140017963950520 whose fp = <socket._fileobject object at 0x7f587966edd0>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
args: 
['git', '--git-dir=/home/tina/Documents/repos/networking/.git', '--work-tree=/home/tina/Documents/repos/networking', 'rev-parse', 'HEAD']
response: 
f921b6945f95f09c3cf2c09e025b97f8f83f1a95

PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=5.24 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=1.52 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=1.54 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=1.50 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 1.507/2.456/5.246/1.610 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=58.5 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=12.2 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 12.207/23.817/58.524/20.038 ms
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 140562933834168 whose fp = <socket._fileobject object at 0x7fd75c236dd0>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
args: 
['git', '--git-dir=/home/tina/Documents/repos/networking/.git', '--work-tree=/home/tina/Documents/repos/networking', 'rev-parse', 'HEAD']
response: 
f921b6945f95f09c3cf2c09e025b97f8f83f1a95

PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=1.30 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=1.43 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=1.54 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=1.70 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 1.304/1.498/1.709/0.153 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=12.1 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.3 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=12.3 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=12.2 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 12.158/12.270/12.355/0.132 ms
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 140440994836920 whose fp = <socket._fileobject object at 0x7fbaf8020dd0>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
response: 
f921b6945f95f09c3cf2c09e025b97f8f83f1a95
PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=1.27 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=1.39 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=16.7 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=1.62 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 1.277/5.252/16.711/6.617 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=12.8 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.3 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=12.4 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=15.5 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 12.345/13.294/15.552/1.321 ms
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 140623935672760 whose fp = <socket._fileobject object at 0x7fe590219dd0>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
response: 
f921b6945f95f09c3cf2c09e025b97f8f83f1a95
monitoring version: 
None
PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=1.80 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=1.54 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=1.51 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=1.54 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 1.514/1.601/1.802/0.123 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=12.3 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.1 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=14.3 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3003ms
rtt min/avg/max/mdev = 12.164/12.751/14.320/0.914 ms
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 140263715234232 whose fp = <socket._fileobject object at 0x7f91b151ddd0>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
monitoring version: 
f921b6945f95f09c3cf2c09e025b97f8f83f1a95
PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=1.31 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=1.54 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=1.69 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=1.62 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 1.318/1.545/1.696/0.144 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=12.3 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=12.5 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3003ms
rtt min/avg/max/mdev = 12.217/12.348/12.568/0.145 ms
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 140541025747384 whose fp = <socket._fileobject object at 0x7fd242507dd0>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
monitoring version: 
f921b6945f95f09c3cf2c09e025b97f8f83f1a95
PING 129.21.67.254 (129.21.67.254) 56(84) bytes of data.
64 bytes from 129.21.67.254: icmp_seq=1 ttl=255 time=1.30 ms
64 bytes from 129.21.67.254: icmp_seq=2 ttl=255 time=1.62 ms
64 bytes from 129.21.67.254: icmp_seq=3 ttl=255 time=1.56 ms
64 bytes from 129.21.67.254: icmp_seq=4 ttl=255 time=17.0 ms

--- 129.21.67.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 1.309/5.392/17.070/6.743 ms
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=12.3 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=12.3 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=12.2 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=12.2 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 12.202/12.276/12.340/0.124 ms
starting status check...
gateway address: 129.21.67.254
pinging gateway...129.21.67.254
response from ping:  0
pinging remote dns address: 8.8.8.8
response from ping:  0
sending http request to remote site: http://python.org/
response object: <addinfourl at 139866260189624 whose fp = <socket._fileobject object at 0x7f3527272e50>>
response code: 200
status check results...
[Gateway Active]: True
[Remote DNS Active]: True
[Remote Site Active]: True
monitoring version: 
f921b6945f95f09c3cf2c09e025b97f8f83f1a95
